<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-NA2E8HP" name="com.stta.SuiteOne.SuiteOneCaseOne" tests="2" failures="1" timestamp="17 Jul 2020 05:04:33 GMT" time="10.221" errors="0">
  <testcase name="SuiteOneCaseOneTest" time="10.209" classname="com.stta.SuiteOne.SuiteOneCaseOne">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ActualResult Value 21 And ExpectedResult Value 22 Not Match expected [22] but found [21]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ActualResult Value 21 And ExpectedResult Value 22 Not Match expected [22] but found [21]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.stta.SuiteOne.SuiteOneCaseOne.SuiteOneCaseOneTest(SuiteOneCaseOne.java:129)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SuiteOneCaseOneTest -->
  <testcase name="SuiteOneCaseOneTest" time="0.012" classname="com.stta.SuiteOne.SuiteOneCaseOne">
    <skipped/>
  </testcase> <!-- SuiteOneCaseOneTest -->
</testsuite> <!-- com.stta.SuiteOne.SuiteOneCaseOne -->
